include: 'https://gitlab.gnome.org/bilelmoussaoui/win32-ci-template/raw/master/ci-template.yml'

stages:
  - deploy
  - win32
variables:
    GIT_SUBMODULE_STRATEGY: recursive

win32:
    variables:
        APP_NAME: "dia"
        BIN_NAME: "dia"
        MANUFACTURER: "GNOME"
        MESON_ARGS: "-Dtests=false"
        VERSION: "0.1"
        BUNDLE: "dia.msi"
        ICON_PATH: "data/icons/scalable/apps/dia.svg"
        GIT_REPO: "https://gitlab.gnome.org/GNOME/dia.git"
        GIT_BRANCH: "bilelmoussaoui/win32"
    extends: .win32

review:
  extends: '.review'

stop_review:
  extends: '.stop_review'
